### ISSUE TITLE
Having a Pull Request Template in the docs ?

### ISSUE THREAD

**Issue by fokusferit** [zalando/zalando-howto-open-source#19]
I just wanted to ask / start the discussion if we should also add a part regarding having a Pull-Request Template in your projects.

Most of the time OSS maintainers are doing PR's for specific Issues and from time to time new contributors might miss to add a related Issue.

For such cases I find it really cool to have a PR Template like [here](https://github.com/wholesale-design-system/components/blob/master/PULL_REQUEST_TEMPLATE.md) or [here](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/).

If yes, I would like to create a PR for this + provide maybe a simple PR Template.

**Comment by lasomethingsomething** [comment]
@fokusferit +1. This would be a great thing to add.

**Comment by fokusferit** [comment]
As it is merged we can close this :)
