### ISSUE TITLE
Consider using the term "FOSS" or "FLOSS" everywhere

### ISSUE THREAD

**Issue by hjacobs** [zalando/zalando-howto-open-source#2]
I think we should make it clearer that the purpose of our "Open Source" efforts is not just purely about "releasing source code" and raising "brand awareness", but also to contribute to society and promote freedom (which is in line with [Radical Agility](https://tech.zalando.com/blog/so-youve-heard-about-radical-agility...-video/)).

That's why we should consider shifting away from the term "Open Source" to a more appropriate "Free and open-source software (FOSS)" or FLOSS.

See also:
- The important four freedoms: https://fsfe.org/about/basics/freesoftware.en.html
- FOSS/FLOSS: https://en.wikipedia.org/wiki/Free_and_open-source_software
- Richard M. Stallmann on the topic (obviously always with strong opinions): https://www.gnu.org/philosophy/floss-and-foss.en.html

These guys decided to use the term "FOSS" everywhere in their policy: https://github.com/18F/open-source-policy/blob/master/policy.md

**Comment by whiskeysierra** [comment]
:+1:

**Comment by lasomethingsomething** [comment]
I remember sharing this idea over the Google Group and getting no response. Let's make a time-hook push for this again when the FSFE fellow visits us June 29 and see if we can get more traction on it.
